spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Sarthak1234
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: FOOD_SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082